### ISSUE TITLE
Support for newer versions of Python3?

### ISSUE THREAD

**Issue by ralexstokes** [ProgVal/rust-python-parser#1]
Are there any plans to support newer features in Python?

In particular, I see that the parser will panic when it tries to read a type annotation like:

```python
foo: int

foo = 22
```

**Comment by progval** [comment]
Sure, I'll work on it

**Comment by progval** [comment]
Actually, that was supposed to be supported already, because I used Python 3.7's grammar when writing this parser. The panic on type annotations was a bug (which is now fixed).

Thanks for the report!

**Comment by ralexstokes** [comment]
Thanks for the quick response! Excited to try it out :)
