### ISSUE TITLE
Multiple `if` statements causes a panic

### ISSUE THREAD

**Issue by ralexstokes** [ProgVal/rust-python-parser#2]
Trying to parse some code and found a problem that seems to be caused with two consecutive `if` statements.

Input:

```python
if True:
    pass
if True:
    pass
```

Causes a panic when parsing the second statement.

**Comment by progval** [comment]
Fixed in ae8ae0fefeb4805ab25dcaa28235e5064cede1e3.

I did some aggressive optimizations in b112e462ad7fec6ed9f7af937b60c3ade1430b21 but forgot to run the test script to check them -_-
